# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MCQ_Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MCQ_Test

  pod 'DLRadioButton', '~> 1.4'
end
